language: python

python:
 - "3.6"

sudo: false

install:
 - pip install pyflakes pycodestyle

script:
 # Run tests
 - tests/run_tests.sh

 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
